const state = { data: null, selected: null, tab: 'diff' };
const detailPreferred = ['15-multi-risk-access-cache','12-indirect-dependency','18-lazy-transaction-boundary'];
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

async function loadBenchmark(){
  const res = await fetch('/benchmark.json');
  state.data = await res.json();
  document.querySelector('#fingerprint').textContent = state.data.fingerprint;
  const detailed = state.data.cases.filter(c => c.diff);
  state.selected = detailed.find(c => detailPreferred.includes(c.id)) || detailed[0] || state.data.cases[0];
  renderCaseList(); renderCase();
}
function renderCaseList(){
  const root = document.querySelector('#caseList');
  root.innerHTML = state.data.cases.map(c => `<button class="case-button ${state.selected?.id===c.id?'active':''}" data-id="${esc(c.id)}"><small>${esc(c.id)} ${c.hard?'· HARD':''}</small>${esc(c.title)} ${c.safe?'<small class="safe">SAFE CONTROL</small>':''}</button>`).join('');
  root.querySelectorAll('button').forEach(btn => btn.addEventListener('click', () => {state.selected = state.data.cases.find(c=>c.id===btn.dataset.id); state.tab='diff'; renderCaseList(); renderCase();}));
}
function renderCase(){
  const c = state.selected;
  document.querySelector('#caseTitle').textContent = c.title;
  document.querySelector('#caseTicket').textContent = c.ticket;
  document.querySelector('#caseBadge').textContent = c.hard ? 'HARD CASE' : (c.safe ? 'SAFE CONTROL' : 'REGRESSION CASE');
  document.querySelector('#caseRisk').textContent = c.safe ? '0 expected risks' : `${c.risk_count} expected risk${c.risk_count===1?'':'s'}`;
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab===state.tab));
  const code = document.querySelector('#caseCode');
  if(!c.diff){
    code.textContent = 'Detailed diff preview is intentionally limited to selected representative cases.\n\nUse `diffradius cases` and the public benchmark source for the complete fixed set.';
    return;
  }
  if(state.tab==='truth') code.textContent = JSON.stringify(c.ground_truth, null, 2);
  else code.textContent = c.diff;
}
document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => {state.tab=tab.dataset.tab; renderCase();}));

async function loadEvidence(){
  try{
    const res = await fetch('/evidence/results/comparison.json', {cache:'no-store'});
    if(!res.ok) throw new Error('not frozen');
    const data = await res.json();
    const order = ['baseline','impact','adversarial','final'];
    document.querySelector('#resultsBody').innerHTML = order.filter(k=>data.stages[k]).map(stage => {
      const v=data.stages[stage];
      return `<tr><td>${esc(stage)}</td><td>${v.f1.toFixed(3)}</td><td>${v.recall.toFixed(3)}</td><td>${v.precision.toFixed(3)}</td><td>${(v.regression_case_detection_rate*100).toFixed(1)}%</td><td>${(v.safe_case_accuracy*100).toFixed(1)}%</td><td>${Number(v.total_tokens).toLocaleString()}</td></tr>`;
    }).join('');
    const box=document.querySelector('#resultsState'); box.classList.remove('pending'); box.classList.add('ready');
    box.querySelector('strong').textContent='Frozen live benchmark evidence loaded';
    box.querySelector('span').textContent='These values come directly from the committed comparison artifact generated by the evaluator.';
    document.querySelector('#resultsTableWrap').classList.remove('hidden');
  }catch(_){ /* pending is an intentional state */ }
}
loadBenchmark().catch(err => {document.querySelector('#caseTitle').textContent='Benchmark failed to load'; console.error(err)});
loadEvidence();
